apiVersion: v1
kind: ConfigMap
metadata: {name: renovate-github-app}
immutable: true
data: {app-id: {{ .Values.appId | quote }}, installation-id: {{ .Values.installationId | quote }}, bot-id: {{ .Values.botId | quote }}}
---
apiVersion: v1
kind: ConfigMap
metadata: {name: renovate-config}
immutable: true
data:
  renovate.json: {{ (.Files.Get "generated/renovate.json") | quote }}
  repositories.json: {{ (.Files.Get "generated/repositories.json") | quote }}
