apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "renovate.appName" . }}
  labels: {app.kubernetes.io/name: renovate}
immutable: true
data:
  app-id: {{ .Values.githubApp.appId | quote }}
  installation-id: {{ .Values.githubApp.installationId | quote }}
  bot-id: {{ .Values.githubApp.botId | quote }}
  bot-login: {{ .Values.githubApp.botLogin | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "renovate.configName" . }}
  labels: {app.kubernetes.io/name: renovate}
immutable: true
data:
  renovate.json: |
{{ include "renovate.config" . | indent 4 }}
  repositories.json: |
{{ ((include "renovate.config" . | fromJson).repositories | toPrettyJson) | indent 4 }}
