githubConfigSecret: arc-github-app
controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc-systems
listenerTemplate:
  spec:
    nodeSelector:
      runner-profile: system
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
        effect: NoSchedule
    containers:
      - name: listener
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
template:
  spec:
    imagePullSecrets:
      - name: ghcr-pull
    nodeSelector:
      runner-profile: container-build
    tolerations:
      - key: runner-profile
        operator: Equal
        value: container-build
        effect: NoSchedule
    securityContext:
      fsGroup: 123
    initContainers:
      - name: init-dind-externals
        image: RUNNER_IMAGE_REQUIRED
        command: [cp, -r, /home/runner/externals/., /home/runner/tmpDir/]
        volumeMounts:
          - name: dind-externals
            mountPath: /home/runner/tmpDir
      - name: dind
        image: docker.io/library/docker@sha256:12e683a161823b2a839aeea999b9d960e6e1f9a97b1679ad6b441982e2d9cf07
        args: [dockerd, "--host=unix:///var/run/docker.sock", "--group=123"]
        env:
          - name: DOCKER_TLS_CERTDIR
            value: ""
        restartPolicy: Always
        securityContext:
          privileged: true
        startupProbe:
          exec:
            command: [docker, info]
          failureThreshold: 24
          periodSeconds: 5
        resources:
          requests:
            cpu: "9"
            memory: 24Gi
          limits:
            cpu: "10"
            memory: 32Gi
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
          - name: dind-externals
            mountPath: /home/runner/externals
          - name: dind-storage
            mountPath: /var/lib/docker
    containers:
      - name: runner
        image: RUNNER_IMAGE_REQUIRED
        imagePullPolicy: IfNotPresent
        command: [/home/runner/run.sh]
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
          - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
            value: "120"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          runAsNonRoot: true
          runAsUser: 1001
        resources:
          requests:
            cpu: "4"
            memory: 8Gi
          limits:
            cpu: "4"
            memory: 12Gi
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
    volumes:
      - name: work
        emptyDir:
          sizeLimit: 50Gi
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}
      - name: dind-storage
        emptyDir:
          sizeLimit: 100Gi
